version: '3.2'

services:
  gomon:
    build: ./gomon
    restart: always
    ports:
    - target: 8080
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host
    depends_on:
      - redis
      - db
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gomon
      MONGO_INITDB_ROOT_PASSWORD: 60M0n
    volumes:
      - /data/mongodb:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: +60M0n+
    volumes:
    - /data/godb:/var/lib/postgresql/data
    ports:
    - target: 5432
      published: 5432
      protocol: tcp
      mode: host

  redis:
    image: redis:alpine
    restart: always
    volumes:
    - /data/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "+g0m0n+"]
    ports:
    - target: 6379
      published: 6379
      mode: host

volumes:
  godb:
  redis:
